/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DominiosTransferirRouteImport } from './routes/dominios.transferir'
import { Route as DominiosRegistrarRouteImport } from './routes/dominios.registrar'
import { Route as DominiosProtecaoWhoisRouteImport } from './routes/dominios.protecao-whois'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedSitesRouteImport } from './routes/_authenticated/sites'
import { Route as AuthenticatedSecurityRouteImport } from './routes/_authenticated/security'
import { Route as AuthenticatedReferralRouteImport } from './routes/_authenticated/referral'
import { Route as AuthenticatedMarketingRouteImport } from './routes/_authenticated/marketing'
import { Route as AuthenticatedLinkbioRouteImport } from './routes/_authenticated/linkbio'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedHostingRouteImport } from './routes/_authenticated/hosting'
import { Route as AuthenticatedEmailsRouteImport } from './routes/_authenticated/emails'
import { Route as AuthenticatedDomainsRouteImport } from './routes/_authenticated/domains'
import { Route as AuthenticatedDesignRouteImport } from './routes/_authenticated/design'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCoursesRouteImport } from './routes/_authenticated/courses'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated/change-password'
import { Route as AuthenticatedAudiovisualRouteImport } from './routes/_authenticated/audiovisual'
import { Route as AuthenticatedAiRouteImport } from './routes/_authenticated/ai'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminServersRouteImport } from './routes/_authenticated/admin/servers'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin/payments'
import { Route as ApiPublicPaymentsMercadopagoWebhookRouteImport } from './routes/api/public/payments/mercadopago/webhook'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DominiosTransferirRoute = DominiosTransferirRouteImport.update({
  id: '/dominios/transferir',
  path: '/dominios/transferir',
  getParentRoute: () => rootRouteImport,
} as any)
const DominiosRegistrarRoute = DominiosRegistrarRouteImport.update({
  id: '/dominios/registrar',
  path: '/dominios/registrar',
  getParentRoute: () => rootRouteImport,
} as any)
const DominiosProtecaoWhoisRoute = DominiosProtecaoWhoisRouteImport.update({
  id: '/dominios/protecao-whois',
  path: '/dominios/protecao-whois',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSitesRoute = AuthenticatedSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSecurityRoute = AuthenticatedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReferralRoute = AuthenticatedReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMarketingRoute = AuthenticatedMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLinkbioRoute = AuthenticatedLinkbioRouteImport.update({
  id: '/linkbio',
  path: '/linkbio',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHostingRoute = AuthenticatedHostingRouteImport.update({
  id: '/hosting',
  path: '/hosting',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmailsRoute = AuthenticatedEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDomainsRoute = AuthenticatedDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDesignRoute = AuthenticatedDesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCoursesRoute = AuthenticatedCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAudiovisualRoute =
  AuthenticatedAudiovisualRouteImport.update({
    id: '/audiovisual',
    path: '/audiovisual',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAiRoute = AuthenticatedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminServersRoute =
  AuthenticatedAdminServersRouteImport.update({
    id: '/admin/servers',
    path: '/admin/servers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/admin/payments',
    path: '/admin/payments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicPaymentsMercadopagoWebhookRoute =
  ApiPublicPaymentsMercadopagoWebhookRouteImport.update({
    id: '/api/public/payments/mercadopago/webhook',
    path: '/api/public/payments/mercadopago/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/account': typeof AuthenticatedAccountRoute
  '/ai': typeof AuthenticatedAiRoute
  '/audiovisual': typeof AuthenticatedAudiovisualRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/courses': typeof AuthenticatedCoursesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/design': typeof AuthenticatedDesignRoute
  '/domains': typeof AuthenticatedDomainsRoute
  '/emails': typeof AuthenticatedEmailsRoute
  '/hosting': typeof AuthenticatedHostingRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/linkbio': typeof AuthenticatedLinkbioRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/referral': typeof AuthenticatedReferralRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/sites': typeof AuthenticatedSitesRoute
  '/support': typeof AuthenticatedSupportRoute
  '/dominios/protecao-whois': typeof DominiosProtecaoWhoisRoute
  '/dominios/registrar': typeof DominiosRegistrarRoute
  '/dominios/transferir': typeof DominiosTransferirRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/servers': typeof AuthenticatedAdminServersRoute
  '/api/public/payments/mercadopago/webhook': typeof ApiPublicPaymentsMercadopagoWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/account': typeof AuthenticatedAccountRoute
  '/ai': typeof AuthenticatedAiRoute
  '/audiovisual': typeof AuthenticatedAudiovisualRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/courses': typeof AuthenticatedCoursesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/design': typeof AuthenticatedDesignRoute
  '/domains': typeof AuthenticatedDomainsRoute
  '/emails': typeof AuthenticatedEmailsRoute
  '/hosting': typeof AuthenticatedHostingRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/linkbio': typeof AuthenticatedLinkbioRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/referral': typeof AuthenticatedReferralRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/sites': typeof AuthenticatedSitesRoute
  '/support': typeof AuthenticatedSupportRoute
  '/dominios/protecao-whois': typeof DominiosProtecaoWhoisRoute
  '/dominios/registrar': typeof DominiosRegistrarRoute
  '/dominios/transferir': typeof DominiosTransferirRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/servers': typeof AuthenticatedAdminServersRoute
  '/api/public/payments/mercadopago/webhook': typeof ApiPublicPaymentsMercadopagoWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/ai': typeof AuthenticatedAiRoute
  '/_authenticated/audiovisual': typeof AuthenticatedAudiovisualRoute
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/courses': typeof AuthenticatedCoursesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/design': typeof AuthenticatedDesignRoute
  '/_authenticated/domains': typeof AuthenticatedDomainsRoute
  '/_authenticated/emails': typeof AuthenticatedEmailsRoute
  '/_authenticated/hosting': typeof AuthenticatedHostingRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRoute
  '/_authenticated/linkbio': typeof AuthenticatedLinkbioRoute
  '/_authenticated/marketing': typeof AuthenticatedMarketingRoute
  '/_authenticated/referral': typeof AuthenticatedReferralRoute
  '/_authenticated/security': typeof AuthenticatedSecurityRoute
  '/_authenticated/sites': typeof AuthenticatedSitesRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/dominios/protecao-whois': typeof DominiosProtecaoWhoisRoute
  '/dominios/registrar': typeof DominiosRegistrarRoute
  '/dominios/transferir': typeof DominiosTransferirRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/servers': typeof AuthenticatedAdminServersRoute
  '/api/public/payments/mercadopago/webhook': typeof ApiPublicPaymentsMercadopagoWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/account'
    | '/ai'
    | '/audiovisual'
    | '/change-password'
    | '/courses'
    | '/dashboard'
    | '/design'
    | '/domains'
    | '/emails'
    | '/hosting'
    | '/invoices'
    | '/linkbio'
    | '/marketing'
    | '/referral'
    | '/security'
    | '/sites'
    | '/support'
    | '/dominios/protecao-whois'
    | '/dominios/registrar'
    | '/dominios/transferir'
    | '/admin/payments'
    | '/admin/servers'
    | '/api/public/payments/mercadopago/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/account'
    | '/ai'
    | '/audiovisual'
    | '/change-password'
    | '/courses'
    | '/dashboard'
    | '/design'
    | '/domains'
    | '/emails'
    | '/hosting'
    | '/invoices'
    | '/linkbio'
    | '/marketing'
    | '/referral'
    | '/security'
    | '/sites'
    | '/support'
    | '/dominios/protecao-whois'
    | '/dominios/registrar'
    | '/dominios/transferir'
    | '/admin/payments'
    | '/admin/servers'
    | '/api/public/payments/mercadopago/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/checkout'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/account'
    | '/_authenticated/ai'
    | '/_authenticated/audiovisual'
    | '/_authenticated/change-password'
    | '/_authenticated/courses'
    | '/_authenticated/dashboard'
    | '/_authenticated/design'
    | '/_authenticated/domains'
    | '/_authenticated/emails'
    | '/_authenticated/hosting'
    | '/_authenticated/invoices'
    | '/_authenticated/linkbio'
    | '/_authenticated/marketing'
    | '/_authenticated/referral'
    | '/_authenticated/security'
    | '/_authenticated/sites'
    | '/_authenticated/support'
    | '/dominios/protecao-whois'
    | '/dominios/registrar'
    | '/dominios/transferir'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/servers'
    | '/api/public/payments/mercadopago/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  DominiosProtecaoWhoisRoute: typeof DominiosProtecaoWhoisRoute
  DominiosRegistrarRoute: typeof DominiosRegistrarRoute
  DominiosTransferirRoute: typeof DominiosTransferirRoute
  ApiPublicPaymentsMercadopagoWebhookRoute: typeof ApiPublicPaymentsMercadopagoWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dominios/transferir': {
      id: '/dominios/transferir'
      path: '/dominios/transferir'
      fullPath: '/dominios/transferir'
      preLoaderRoute: typeof DominiosTransferirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dominios/registrar': {
      id: '/dominios/registrar'
      path: '/dominios/registrar'
      fullPath: '/dominios/registrar'
      preLoaderRoute: typeof DominiosRegistrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dominios/protecao-whois': {
      id: '/dominios/protecao-whois'
      path: '/dominios/protecao-whois'
      fullPath: '/dominios/protecao-whois'
      preLoaderRoute: typeof DominiosProtecaoWhoisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sites': {
      id: '/_authenticated/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof AuthenticatedSitesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/security': {
      id: '/_authenticated/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthenticatedSecurityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/referral': {
      id: '/_authenticated/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof AuthenticatedReferralRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketing': {
      id: '/_authenticated/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AuthenticatedMarketingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/linkbio': {
      id: '/_authenticated/linkbio'
      path: '/linkbio'
      fullPath: '/linkbio'
      preLoaderRoute: typeof AuthenticatedLinkbioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hosting': {
      id: '/_authenticated/hosting'
      path: '/hosting'
      fullPath: '/hosting'
      preLoaderRoute: typeof AuthenticatedHostingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/emails': {
      id: '/_authenticated/emails'
      path: '/emails'
      fullPath: '/emails'
      preLoaderRoute: typeof AuthenticatedEmailsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/domains': {
      id: '/_authenticated/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof AuthenticatedDomainsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/design': {
      id: '/_authenticated/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof AuthenticatedDesignRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/courses': {
      id: '/_authenticated/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AuthenticatedCoursesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audiovisual': {
      id: '/_authenticated/audiovisual'
      path: '/audiovisual'
      fullPath: '/audiovisual'
      preLoaderRoute: typeof AuthenticatedAudiovisualRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai': {
      id: '/_authenticated/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/servers': {
      id: '/_authenticated/admin/servers'
      path: '/admin/servers'
      fullPath: '/admin/servers'
      preLoaderRoute: typeof AuthenticatedAdminServersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/payments/mercadopago/webhook': {
      id: '/api/public/payments/mercadopago/webhook'
      path: '/api/public/payments/mercadopago/webhook'
      fullPath: '/api/public/payments/mercadopago/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsMercadopagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAiRoute: typeof AuthenticatedAiRoute
  AuthenticatedAudiovisualRoute: typeof AuthenticatedAudiovisualRoute
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
  AuthenticatedCoursesRoute: typeof AuthenticatedCoursesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDesignRoute: typeof AuthenticatedDesignRoute
  AuthenticatedDomainsRoute: typeof AuthenticatedDomainsRoute
  AuthenticatedEmailsRoute: typeof AuthenticatedEmailsRoute
  AuthenticatedHostingRoute: typeof AuthenticatedHostingRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRoute
  AuthenticatedLinkbioRoute: typeof AuthenticatedLinkbioRoute
  AuthenticatedMarketingRoute: typeof AuthenticatedMarketingRoute
  AuthenticatedReferralRoute: typeof AuthenticatedReferralRoute
  AuthenticatedSecurityRoute: typeof AuthenticatedSecurityRoute
  AuthenticatedSitesRoute: typeof AuthenticatedSitesRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminServersRoute: typeof AuthenticatedAdminServersRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAiRoute: AuthenticatedAiRoute,
  AuthenticatedAudiovisualRoute: AuthenticatedAudiovisualRoute,
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
  AuthenticatedCoursesRoute: AuthenticatedCoursesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDesignRoute: AuthenticatedDesignRoute,
  AuthenticatedDomainsRoute: AuthenticatedDomainsRoute,
  AuthenticatedEmailsRoute: AuthenticatedEmailsRoute,
  AuthenticatedHostingRoute: AuthenticatedHostingRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRoute,
  AuthenticatedLinkbioRoute: AuthenticatedLinkbioRoute,
  AuthenticatedMarketingRoute: AuthenticatedMarketingRoute,
  AuthenticatedReferralRoute: AuthenticatedReferralRoute,
  AuthenticatedSecurityRoute: AuthenticatedSecurityRoute,
  AuthenticatedSitesRoute: AuthenticatedSitesRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminServersRoute: AuthenticatedAdminServersRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  DominiosProtecaoWhoisRoute: DominiosProtecaoWhoisRoute,
  DominiosRegistrarRoute: DominiosRegistrarRoute,
  DominiosTransferirRoute: DominiosTransferirRoute,
  ApiPublicPaymentsMercadopagoWebhookRoute:
    ApiPublicPaymentsMercadopagoWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
