/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as NossoEscritorioRouteImport } from './routes/nosso-escritorio'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DesignRouteImport } from './routes/design'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CertificadosSslRouteImport } from './routes/certificados-ssl'
import { Route as AudiovisualRouteImport } from './routes/audiovisual'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VpsCloudVpsNvmeRouteImport } from './routes/vps-cloud.vps-nvme'
import { Route as VpsCloudServidorDedicadoRouteImport } from './routes/vps-cloud.servidor-dedicado'
import { Route as VpsCloudCloudPrivadaRouteImport } from './routes/vps-cloud.cloud-privada'
import { Route as MarketingTrafegoPagoRouteImport } from './routes/marketing.trafego-pago'
import { Route as MarketingSeoPremiumRouteImport } from './routes/marketing.seo-premium'
import { Route as MarketingGestaoSocialRouteImport } from './routes/marketing.gestao-social'
import { Route as IaAutomacaoOpenclawRouteImport } from './routes/ia-automacao.openclaw'
import { Route as IaAutomacaoIaWhatsappRouteImport } from './routes/ia-automacao.ia-whatsapp'
import { Route as IaAutomacaoChatbotsIaRouteImport } from './routes/ia-automacao.chatbots-ia'
import { Route as IaAutomacaoAutomacaoN8nRouteImport } from './routes/ia-automacao.automacao-n8n'
import { Route as HospedagemWebRouteImport } from './routes/hospedagem.web'
import { Route as HospedagemRevendaWhmRouteImport } from './routes/hospedagem.revenda-whm'
import { Route as HospedagemEmailCorporativoRouteImport } from './routes/hospedagem.email-corporativo'
import { Route as HospedagemCloudRouteImport } from './routes/hospedagem.cloud'
import { Route as DominiosTransferirRouteImport } from './routes/dominios.transferir'
import { Route as DominiosRegistrarRouteImport } from './routes/dominios.registrar'
import { Route as DominiosProtecaoWhoisRouteImport } from './routes/dominios.protecao-whois'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedSitesRouteImport } from './routes/_authenticated/sites'
import { Route as AuthenticatedSecurityRouteImport } from './routes/_authenticated/security'
import { Route as AuthenticatedReferralRouteImport } from './routes/_authenticated/referral'
import { Route as AuthenticatedMeuDesignRouteImport } from './routes/_authenticated/meu-design'
import { Route as AuthenticatedMeuAudiovisualRouteImport } from './routes/_authenticated/meu-audiovisual'
import { Route as AuthenticatedMarketingRouteImport } from './routes/_authenticated/marketing'
import { Route as AuthenticatedLinkbioRouteImport } from './routes/_authenticated/linkbio'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedHostingRouteImport } from './routes/_authenticated/hosting'
import { Route as AuthenticatedEmailsRouteImport } from './routes/_authenticated/emails'
import { Route as AuthenticatedDomainsRouteImport } from './routes/_authenticated/domains'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCoursesRouteImport } from './routes/_authenticated/courses'
import { Route as AuthenticatedChangePasswordRouteImport } from './routes/_authenticated/change-password'
import { Route as AuthenticatedAiRouteImport } from './routes/_authenticated/ai'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedAdminServersRouteImport } from './routes/_authenticated/admin/servers'
import { Route as AuthenticatedAdminPaymentsRouteImport } from './routes/_authenticated/admin/payments'
import { Route as ApiPublicPaymentsMercadopagoWebhookRouteImport } from './routes/api/public/payments/mercadopago/webhook'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const NossoEscritorioRoute = NossoEscritorioRouteImport.update({
  id: '/nosso-escritorio',
  path: '/nosso-escritorio',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignRoute = DesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificadosSslRoute = CertificadosSslRouteImport.update({
  id: '/certificados-ssl',
  path: '/certificados-ssl',
  getParentRoute: () => rootRouteImport,
} as any)
const AudiovisualRoute = AudiovisualRouteImport.update({
  id: '/audiovisual',
  path: '/audiovisual',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VpsCloudVpsNvmeRoute = VpsCloudVpsNvmeRouteImport.update({
  id: '/vps-cloud/vps-nvme',
  path: '/vps-cloud/vps-nvme',
  getParentRoute: () => rootRouteImport,
} as any)
const VpsCloudServidorDedicadoRoute =
  VpsCloudServidorDedicadoRouteImport.update({
    id: '/vps-cloud/servidor-dedicado',
    path: '/vps-cloud/servidor-dedicado',
    getParentRoute: () => rootRouteImport,
  } as any)
const VpsCloudCloudPrivadaRoute = VpsCloudCloudPrivadaRouteImport.update({
  id: '/vps-cloud/cloud-privada',
  path: '/vps-cloud/cloud-privada',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingTrafegoPagoRoute = MarketingTrafegoPagoRouteImport.update({
  id: '/marketing/trafego-pago',
  path: '/marketing/trafego-pago',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingSeoPremiumRoute = MarketingSeoPremiumRouteImport.update({
  id: '/marketing/seo-premium',
  path: '/marketing/seo-premium',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingGestaoSocialRoute = MarketingGestaoSocialRouteImport.update({
  id: '/marketing/gestao-social',
  path: '/marketing/gestao-social',
  getParentRoute: () => rootRouteImport,
} as any)
const IaAutomacaoOpenclawRoute = IaAutomacaoOpenclawRouteImport.update({
  id: '/ia-automacao/openclaw',
  path: '/ia-automacao/openclaw',
  getParentRoute: () => rootRouteImport,
} as any)
const IaAutomacaoIaWhatsappRoute = IaAutomacaoIaWhatsappRouteImport.update({
  id: '/ia-automacao/ia-whatsapp',
  path: '/ia-automacao/ia-whatsapp',
  getParentRoute: () => rootRouteImport,
} as any)
const IaAutomacaoChatbotsIaRoute = IaAutomacaoChatbotsIaRouteImport.update({
  id: '/ia-automacao/chatbots-ia',
  path: '/ia-automacao/chatbots-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const IaAutomacaoAutomacaoN8nRoute = IaAutomacaoAutomacaoN8nRouteImport.update({
  id: '/ia-automacao/automacao-n8n',
  path: '/ia-automacao/automacao-n8n',
  getParentRoute: () => rootRouteImport,
} as any)
const HospedagemWebRoute = HospedagemWebRouteImport.update({
  id: '/hospedagem/web',
  path: '/hospedagem/web',
  getParentRoute: () => rootRouteImport,
} as any)
const HospedagemRevendaWhmRoute = HospedagemRevendaWhmRouteImport.update({
  id: '/hospedagem/revenda-whm',
  path: '/hospedagem/revenda-whm',
  getParentRoute: () => rootRouteImport,
} as any)
const HospedagemEmailCorporativoRoute =
  HospedagemEmailCorporativoRouteImport.update({
    id: '/hospedagem/email-corporativo',
    path: '/hospedagem/email-corporativo',
    getParentRoute: () => rootRouteImport,
  } as any)
const HospedagemCloudRoute = HospedagemCloudRouteImport.update({
  id: '/hospedagem/cloud',
  path: '/hospedagem/cloud',
  getParentRoute: () => rootRouteImport,
} as any)
const DominiosTransferirRoute = DominiosTransferirRouteImport.update({
  id: '/dominios/transferir',
  path: '/dominios/transferir',
  getParentRoute: () => rootRouteImport,
} as any)
const DominiosRegistrarRoute = DominiosRegistrarRouteImport.update({
  id: '/dominios/registrar',
  path: '/dominios/registrar',
  getParentRoute: () => rootRouteImport,
} as any)
const DominiosProtecaoWhoisRoute = DominiosProtecaoWhoisRouteImport.update({
  id: '/dominios/protecao-whois',
  path: '/dominios/protecao-whois',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSitesRoute = AuthenticatedSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSecurityRoute = AuthenticatedSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReferralRoute = AuthenticatedReferralRouteImport.update({
  id: '/referral',
  path: '/referral',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeuDesignRoute = AuthenticatedMeuDesignRouteImport.update({
  id: '/meu-design',
  path: '/meu-design',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMeuAudiovisualRoute =
  AuthenticatedMeuAudiovisualRouteImport.update({
    id: '/meu-audiovisual',
    path: '/meu-audiovisual',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMarketingRoute = AuthenticatedMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLinkbioRoute = AuthenticatedLinkbioRouteImport.update({
  id: '/linkbio',
  path: '/linkbio',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHostingRoute = AuthenticatedHostingRouteImport.update({
  id: '/hosting',
  path: '/hosting',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEmailsRoute = AuthenticatedEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDomainsRoute = AuthenticatedDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCoursesRoute = AuthenticatedCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChangePasswordRoute =
  AuthenticatedChangePasswordRouteImport.update({
    id: '/change-password',
    path: '/change-password',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAiRoute = AuthenticatedAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminServersRoute =
  AuthenticatedAdminServersRouteImport.update({
    id: '/admin/servers',
    path: '/admin/servers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminPaymentsRoute =
  AuthenticatedAdminPaymentsRouteImport.update({
    id: '/admin/payments',
    path: '/admin/payments',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicPaymentsMercadopagoWebhookRoute =
  ApiPublicPaymentsMercadopagoWebhookRouteImport.update({
    id: '/api/public/payments/mercadopago/webhook',
    path: '/api/public/payments/mercadopago/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audiovisual': typeof AudiovisualRoute
  '/certificados-ssl': typeof CertificadosSslRoute
  '/checkout': typeof CheckoutRoute
  '/contacto': typeof ContactoRoute
  '/design': typeof DesignRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/nosso-escritorio': typeof NossoEscritorioRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/account': typeof AuthenticatedAccountRoute
  '/ai': typeof AuthenticatedAiRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/courses': typeof AuthenticatedCoursesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/domains': typeof AuthenticatedDomainsRoute
  '/emails': typeof AuthenticatedEmailsRoute
  '/hosting': typeof AuthenticatedHostingRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/linkbio': typeof AuthenticatedLinkbioRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/meu-audiovisual': typeof AuthenticatedMeuAudiovisualRoute
  '/meu-design': typeof AuthenticatedMeuDesignRoute
  '/referral': typeof AuthenticatedReferralRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/sites': typeof AuthenticatedSitesRoute
  '/support': typeof AuthenticatedSupportRoute
  '/dominios/protecao-whois': typeof DominiosProtecaoWhoisRoute
  '/dominios/registrar': typeof DominiosRegistrarRoute
  '/dominios/transferir': typeof DominiosTransferirRoute
  '/hospedagem/cloud': typeof HospedagemCloudRoute
  '/hospedagem/email-corporativo': typeof HospedagemEmailCorporativoRoute
  '/hospedagem/revenda-whm': typeof HospedagemRevendaWhmRoute
  '/hospedagem/web': typeof HospedagemWebRoute
  '/ia-automacao/automacao-n8n': typeof IaAutomacaoAutomacaoN8nRoute
  '/ia-automacao/chatbots-ia': typeof IaAutomacaoChatbotsIaRoute
  '/ia-automacao/ia-whatsapp': typeof IaAutomacaoIaWhatsappRoute
  '/ia-automacao/openclaw': typeof IaAutomacaoOpenclawRoute
  '/marketing/gestao-social': typeof MarketingGestaoSocialRoute
  '/marketing/seo-premium': typeof MarketingSeoPremiumRoute
  '/marketing/trafego-pago': typeof MarketingTrafegoPagoRoute
  '/vps-cloud/cloud-privada': typeof VpsCloudCloudPrivadaRoute
  '/vps-cloud/servidor-dedicado': typeof VpsCloudServidorDedicadoRoute
  '/vps-cloud/vps-nvme': typeof VpsCloudVpsNvmeRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/servers': typeof AuthenticatedAdminServersRoute
  '/api/public/payments/mercadopago/webhook': typeof ApiPublicPaymentsMercadopagoWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audiovisual': typeof AudiovisualRoute
  '/certificados-ssl': typeof CertificadosSslRoute
  '/checkout': typeof CheckoutRoute
  '/contacto': typeof ContactoRoute
  '/design': typeof DesignRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/nosso-escritorio': typeof NossoEscritorioRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/account': typeof AuthenticatedAccountRoute
  '/ai': typeof AuthenticatedAiRoute
  '/change-password': typeof AuthenticatedChangePasswordRoute
  '/courses': typeof AuthenticatedCoursesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/domains': typeof AuthenticatedDomainsRoute
  '/emails': typeof AuthenticatedEmailsRoute
  '/hosting': typeof AuthenticatedHostingRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/linkbio': typeof AuthenticatedLinkbioRoute
  '/marketing': typeof AuthenticatedMarketingRoute
  '/meu-audiovisual': typeof AuthenticatedMeuAudiovisualRoute
  '/meu-design': typeof AuthenticatedMeuDesignRoute
  '/referral': typeof AuthenticatedReferralRoute
  '/security': typeof AuthenticatedSecurityRoute
  '/sites': typeof AuthenticatedSitesRoute
  '/support': typeof AuthenticatedSupportRoute
  '/dominios/protecao-whois': typeof DominiosProtecaoWhoisRoute
  '/dominios/registrar': typeof DominiosRegistrarRoute
  '/dominios/transferir': typeof DominiosTransferirRoute
  '/hospedagem/cloud': typeof HospedagemCloudRoute
  '/hospedagem/email-corporativo': typeof HospedagemEmailCorporativoRoute
  '/hospedagem/revenda-whm': typeof HospedagemRevendaWhmRoute
  '/hospedagem/web': typeof HospedagemWebRoute
  '/ia-automacao/automacao-n8n': typeof IaAutomacaoAutomacaoN8nRoute
  '/ia-automacao/chatbots-ia': typeof IaAutomacaoChatbotsIaRoute
  '/ia-automacao/ia-whatsapp': typeof IaAutomacaoIaWhatsappRoute
  '/ia-automacao/openclaw': typeof IaAutomacaoOpenclawRoute
  '/marketing/gestao-social': typeof MarketingGestaoSocialRoute
  '/marketing/seo-premium': typeof MarketingSeoPremiumRoute
  '/marketing/trafego-pago': typeof MarketingTrafegoPagoRoute
  '/vps-cloud/cloud-privada': typeof VpsCloudCloudPrivadaRoute
  '/vps-cloud/servidor-dedicado': typeof VpsCloudServidorDedicadoRoute
  '/vps-cloud/vps-nvme': typeof VpsCloudVpsNvmeRoute
  '/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/admin/servers': typeof AuthenticatedAdminServersRoute
  '/api/public/payments/mercadopago/webhook': typeof ApiPublicPaymentsMercadopagoWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/audiovisual': typeof AudiovisualRoute
  '/certificados-ssl': typeof CertificadosSslRoute
  '/checkout': typeof CheckoutRoute
  '/contacto': typeof ContactoRoute
  '/design': typeof DesignRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/nosso-escritorio': typeof NossoEscritorioRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/ai': typeof AuthenticatedAiRoute
  '/_authenticated/change-password': typeof AuthenticatedChangePasswordRoute
  '/_authenticated/courses': typeof AuthenticatedCoursesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/domains': typeof AuthenticatedDomainsRoute
  '/_authenticated/emails': typeof AuthenticatedEmailsRoute
  '/_authenticated/hosting': typeof AuthenticatedHostingRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRoute
  '/_authenticated/linkbio': typeof AuthenticatedLinkbioRoute
  '/_authenticated/marketing': typeof AuthenticatedMarketingRoute
  '/_authenticated/meu-audiovisual': typeof AuthenticatedMeuAudiovisualRoute
  '/_authenticated/meu-design': typeof AuthenticatedMeuDesignRoute
  '/_authenticated/referral': typeof AuthenticatedReferralRoute
  '/_authenticated/security': typeof AuthenticatedSecurityRoute
  '/_authenticated/sites': typeof AuthenticatedSitesRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/dominios/protecao-whois': typeof DominiosProtecaoWhoisRoute
  '/dominios/registrar': typeof DominiosRegistrarRoute
  '/dominios/transferir': typeof DominiosTransferirRoute
  '/hospedagem/cloud': typeof HospedagemCloudRoute
  '/hospedagem/email-corporativo': typeof HospedagemEmailCorporativoRoute
  '/hospedagem/revenda-whm': typeof HospedagemRevendaWhmRoute
  '/hospedagem/web': typeof HospedagemWebRoute
  '/ia-automacao/automacao-n8n': typeof IaAutomacaoAutomacaoN8nRoute
  '/ia-automacao/chatbots-ia': typeof IaAutomacaoChatbotsIaRoute
  '/ia-automacao/ia-whatsapp': typeof IaAutomacaoIaWhatsappRoute
  '/ia-automacao/openclaw': typeof IaAutomacaoOpenclawRoute
  '/marketing/gestao-social': typeof MarketingGestaoSocialRoute
  '/marketing/seo-premium': typeof MarketingSeoPremiumRoute
  '/marketing/trafego-pago': typeof MarketingTrafegoPagoRoute
  '/vps-cloud/cloud-privada': typeof VpsCloudCloudPrivadaRoute
  '/vps-cloud/servidor-dedicado': typeof VpsCloudServidorDedicadoRoute
  '/vps-cloud/vps-nvme': typeof VpsCloudVpsNvmeRoute
  '/_authenticated/admin/payments': typeof AuthenticatedAdminPaymentsRoute
  '/_authenticated/admin/servers': typeof AuthenticatedAdminServersRoute
  '/api/public/payments/mercadopago/webhook': typeof ApiPublicPaymentsMercadopagoWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audiovisual'
    | '/certificados-ssl'
    | '/checkout'
    | '/contacto'
    | '/design'
    | '/forgot-password'
    | '/login'
    | '/nosso-escritorio'
    | '/reset-password'
    | '/signup'
    | '/account'
    | '/ai'
    | '/change-password'
    | '/courses'
    | '/dashboard'
    | '/domains'
    | '/emails'
    | '/hosting'
    | '/invoices'
    | '/linkbio'
    | '/marketing'
    | '/meu-audiovisual'
    | '/meu-design'
    | '/referral'
    | '/security'
    | '/sites'
    | '/support'
    | '/dominios/protecao-whois'
    | '/dominios/registrar'
    | '/dominios/transferir'
    | '/hospedagem/cloud'
    | '/hospedagem/email-corporativo'
    | '/hospedagem/revenda-whm'
    | '/hospedagem/web'
    | '/ia-automacao/automacao-n8n'
    | '/ia-automacao/chatbots-ia'
    | '/ia-automacao/ia-whatsapp'
    | '/ia-automacao/openclaw'
    | '/marketing/gestao-social'
    | '/marketing/seo-premium'
    | '/marketing/trafego-pago'
    | '/vps-cloud/cloud-privada'
    | '/vps-cloud/servidor-dedicado'
    | '/vps-cloud/vps-nvme'
    | '/admin/payments'
    | '/admin/servers'
    | '/api/public/payments/mercadopago/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audiovisual'
    | '/certificados-ssl'
    | '/checkout'
    | '/contacto'
    | '/design'
    | '/forgot-password'
    | '/login'
    | '/nosso-escritorio'
    | '/reset-password'
    | '/signup'
    | '/account'
    | '/ai'
    | '/change-password'
    | '/courses'
    | '/dashboard'
    | '/domains'
    | '/emails'
    | '/hosting'
    | '/invoices'
    | '/linkbio'
    | '/marketing'
    | '/meu-audiovisual'
    | '/meu-design'
    | '/referral'
    | '/security'
    | '/sites'
    | '/support'
    | '/dominios/protecao-whois'
    | '/dominios/registrar'
    | '/dominios/transferir'
    | '/hospedagem/cloud'
    | '/hospedagem/email-corporativo'
    | '/hospedagem/revenda-whm'
    | '/hospedagem/web'
    | '/ia-automacao/automacao-n8n'
    | '/ia-automacao/chatbots-ia'
    | '/ia-automacao/ia-whatsapp'
    | '/ia-automacao/openclaw'
    | '/marketing/gestao-social'
    | '/marketing/seo-premium'
    | '/marketing/trafego-pago'
    | '/vps-cloud/cloud-privada'
    | '/vps-cloud/servidor-dedicado'
    | '/vps-cloud/vps-nvme'
    | '/admin/payments'
    | '/admin/servers'
    | '/api/public/payments/mercadopago/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/audiovisual'
    | '/certificados-ssl'
    | '/checkout'
    | '/contacto'
    | '/design'
    | '/forgot-password'
    | '/login'
    | '/nosso-escritorio'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/account'
    | '/_authenticated/ai'
    | '/_authenticated/change-password'
    | '/_authenticated/courses'
    | '/_authenticated/dashboard'
    | '/_authenticated/domains'
    | '/_authenticated/emails'
    | '/_authenticated/hosting'
    | '/_authenticated/invoices'
    | '/_authenticated/linkbio'
    | '/_authenticated/marketing'
    | '/_authenticated/meu-audiovisual'
    | '/_authenticated/meu-design'
    | '/_authenticated/referral'
    | '/_authenticated/security'
    | '/_authenticated/sites'
    | '/_authenticated/support'
    | '/dominios/protecao-whois'
    | '/dominios/registrar'
    | '/dominios/transferir'
    | '/hospedagem/cloud'
    | '/hospedagem/email-corporativo'
    | '/hospedagem/revenda-whm'
    | '/hospedagem/web'
    | '/ia-automacao/automacao-n8n'
    | '/ia-automacao/chatbots-ia'
    | '/ia-automacao/ia-whatsapp'
    | '/ia-automacao/openclaw'
    | '/marketing/gestao-social'
    | '/marketing/seo-premium'
    | '/marketing/trafego-pago'
    | '/vps-cloud/cloud-privada'
    | '/vps-cloud/servidor-dedicado'
    | '/vps-cloud/vps-nvme'
    | '/_authenticated/admin/payments'
    | '/_authenticated/admin/servers'
    | '/api/public/payments/mercadopago/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AudiovisualRoute: typeof AudiovisualRoute
  CertificadosSslRoute: typeof CertificadosSslRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactoRoute: typeof ContactoRoute
  DesignRoute: typeof DesignRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  NossoEscritorioRoute: typeof NossoEscritorioRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  DominiosProtecaoWhoisRoute: typeof DominiosProtecaoWhoisRoute
  DominiosRegistrarRoute: typeof DominiosRegistrarRoute
  DominiosTransferirRoute: typeof DominiosTransferirRoute
  HospedagemCloudRoute: typeof HospedagemCloudRoute
  HospedagemEmailCorporativoRoute: typeof HospedagemEmailCorporativoRoute
  HospedagemRevendaWhmRoute: typeof HospedagemRevendaWhmRoute
  HospedagemWebRoute: typeof HospedagemWebRoute
  IaAutomacaoAutomacaoN8nRoute: typeof IaAutomacaoAutomacaoN8nRoute
  IaAutomacaoChatbotsIaRoute: typeof IaAutomacaoChatbotsIaRoute
  IaAutomacaoIaWhatsappRoute: typeof IaAutomacaoIaWhatsappRoute
  IaAutomacaoOpenclawRoute: typeof IaAutomacaoOpenclawRoute
  MarketingGestaoSocialRoute: typeof MarketingGestaoSocialRoute
  MarketingSeoPremiumRoute: typeof MarketingSeoPremiumRoute
  MarketingTrafegoPagoRoute: typeof MarketingTrafegoPagoRoute
  VpsCloudCloudPrivadaRoute: typeof VpsCloudCloudPrivadaRoute
  VpsCloudServidorDedicadoRoute: typeof VpsCloudServidorDedicadoRoute
  VpsCloudVpsNvmeRoute: typeof VpsCloudVpsNvmeRoute
  ApiPublicPaymentsMercadopagoWebhookRoute: typeof ApiPublicPaymentsMercadopagoWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosso-escritorio': {
      id: '/nosso-escritorio'
      path: '/nosso-escritorio'
      fullPath: '/nosso-escritorio'
      preLoaderRoute: typeof NossoEscritorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design': {
      id: '/design'
      path: '/design'
      fullPath: '/design'
      preLoaderRoute: typeof DesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificados-ssl': {
      id: '/certificados-ssl'
      path: '/certificados-ssl'
      fullPath: '/certificados-ssl'
      preLoaderRoute: typeof CertificadosSslRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audiovisual': {
      id: '/audiovisual'
      path: '/audiovisual'
      fullPath: '/audiovisual'
      preLoaderRoute: typeof AudiovisualRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vps-cloud/vps-nvme': {
      id: '/vps-cloud/vps-nvme'
      path: '/vps-cloud/vps-nvme'
      fullPath: '/vps-cloud/vps-nvme'
      preLoaderRoute: typeof VpsCloudVpsNvmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vps-cloud/servidor-dedicado': {
      id: '/vps-cloud/servidor-dedicado'
      path: '/vps-cloud/servidor-dedicado'
      fullPath: '/vps-cloud/servidor-dedicado'
      preLoaderRoute: typeof VpsCloudServidorDedicadoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vps-cloud/cloud-privada': {
      id: '/vps-cloud/cloud-privada'
      path: '/vps-cloud/cloud-privada'
      fullPath: '/vps-cloud/cloud-privada'
      preLoaderRoute: typeof VpsCloudCloudPrivadaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/trafego-pago': {
      id: '/marketing/trafego-pago'
      path: '/marketing/trafego-pago'
      fullPath: '/marketing/trafego-pago'
      preLoaderRoute: typeof MarketingTrafegoPagoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/seo-premium': {
      id: '/marketing/seo-premium'
      path: '/marketing/seo-premium'
      fullPath: '/marketing/seo-premium'
      preLoaderRoute: typeof MarketingSeoPremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing/gestao-social': {
      id: '/marketing/gestao-social'
      path: '/marketing/gestao-social'
      fullPath: '/marketing/gestao-social'
      preLoaderRoute: typeof MarketingGestaoSocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia-automacao/openclaw': {
      id: '/ia-automacao/openclaw'
      path: '/ia-automacao/openclaw'
      fullPath: '/ia-automacao/openclaw'
      preLoaderRoute: typeof IaAutomacaoOpenclawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia-automacao/ia-whatsapp': {
      id: '/ia-automacao/ia-whatsapp'
      path: '/ia-automacao/ia-whatsapp'
      fullPath: '/ia-automacao/ia-whatsapp'
      preLoaderRoute: typeof IaAutomacaoIaWhatsappRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia-automacao/chatbots-ia': {
      id: '/ia-automacao/chatbots-ia'
      path: '/ia-automacao/chatbots-ia'
      fullPath: '/ia-automacao/chatbots-ia'
      preLoaderRoute: typeof IaAutomacaoChatbotsIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ia-automacao/automacao-n8n': {
      id: '/ia-automacao/automacao-n8n'
      path: '/ia-automacao/automacao-n8n'
      fullPath: '/ia-automacao/automacao-n8n'
      preLoaderRoute: typeof IaAutomacaoAutomacaoN8nRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospedagem/web': {
      id: '/hospedagem/web'
      path: '/hospedagem/web'
      fullPath: '/hospedagem/web'
      preLoaderRoute: typeof HospedagemWebRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospedagem/revenda-whm': {
      id: '/hospedagem/revenda-whm'
      path: '/hospedagem/revenda-whm'
      fullPath: '/hospedagem/revenda-whm'
      preLoaderRoute: typeof HospedagemRevendaWhmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospedagem/email-corporativo': {
      id: '/hospedagem/email-corporativo'
      path: '/hospedagem/email-corporativo'
      fullPath: '/hospedagem/email-corporativo'
      preLoaderRoute: typeof HospedagemEmailCorporativoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hospedagem/cloud': {
      id: '/hospedagem/cloud'
      path: '/hospedagem/cloud'
      fullPath: '/hospedagem/cloud'
      preLoaderRoute: typeof HospedagemCloudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dominios/transferir': {
      id: '/dominios/transferir'
      path: '/dominios/transferir'
      fullPath: '/dominios/transferir'
      preLoaderRoute: typeof DominiosTransferirRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dominios/registrar': {
      id: '/dominios/registrar'
      path: '/dominios/registrar'
      fullPath: '/dominios/registrar'
      preLoaderRoute: typeof DominiosRegistrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dominios/protecao-whois': {
      id: '/dominios/protecao-whois'
      path: '/dominios/protecao-whois'
      fullPath: '/dominios/protecao-whois'
      preLoaderRoute: typeof DominiosProtecaoWhoisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sites': {
      id: '/_authenticated/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof AuthenticatedSitesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/security': {
      id: '/_authenticated/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof AuthenticatedSecurityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/referral': {
      id: '/_authenticated/referral'
      path: '/referral'
      fullPath: '/referral'
      preLoaderRoute: typeof AuthenticatedReferralRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meu-design': {
      id: '/_authenticated/meu-design'
      path: '/meu-design'
      fullPath: '/meu-design'
      preLoaderRoute: typeof AuthenticatedMeuDesignRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meu-audiovisual': {
      id: '/_authenticated/meu-audiovisual'
      path: '/meu-audiovisual'
      fullPath: '/meu-audiovisual'
      preLoaderRoute: typeof AuthenticatedMeuAudiovisualRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketing': {
      id: '/_authenticated/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof AuthenticatedMarketingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/linkbio': {
      id: '/_authenticated/linkbio'
      path: '/linkbio'
      fullPath: '/linkbio'
      preLoaderRoute: typeof AuthenticatedLinkbioRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/hosting': {
      id: '/_authenticated/hosting'
      path: '/hosting'
      fullPath: '/hosting'
      preLoaderRoute: typeof AuthenticatedHostingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/emails': {
      id: '/_authenticated/emails'
      path: '/emails'
      fullPath: '/emails'
      preLoaderRoute: typeof AuthenticatedEmailsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/domains': {
      id: '/_authenticated/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof AuthenticatedDomainsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/courses': {
      id: '/_authenticated/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AuthenticatedCoursesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/change-password': {
      id: '/_authenticated/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof AuthenticatedChangePasswordRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ai': {
      id: '/_authenticated/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AuthenticatedAiRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/servers': {
      id: '/_authenticated/admin/servers'
      path: '/admin/servers'
      fullPath: '/admin/servers'
      preLoaderRoute: typeof AuthenticatedAdminServersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/payments': {
      id: '/_authenticated/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AuthenticatedAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/payments/mercadopago/webhook': {
      id: '/api/public/payments/mercadopago/webhook'
      path: '/api/public/payments/mercadopago/webhook'
      fullPath: '/api/public/payments/mercadopago/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsMercadopagoWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedAiRoute: typeof AuthenticatedAiRoute
  AuthenticatedChangePasswordRoute: typeof AuthenticatedChangePasswordRoute
  AuthenticatedCoursesRoute: typeof AuthenticatedCoursesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDomainsRoute: typeof AuthenticatedDomainsRoute
  AuthenticatedEmailsRoute: typeof AuthenticatedEmailsRoute
  AuthenticatedHostingRoute: typeof AuthenticatedHostingRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRoute
  AuthenticatedLinkbioRoute: typeof AuthenticatedLinkbioRoute
  AuthenticatedMarketingRoute: typeof AuthenticatedMarketingRoute
  AuthenticatedMeuAudiovisualRoute: typeof AuthenticatedMeuAudiovisualRoute
  AuthenticatedMeuDesignRoute: typeof AuthenticatedMeuDesignRoute
  AuthenticatedReferralRoute: typeof AuthenticatedReferralRoute
  AuthenticatedSecurityRoute: typeof AuthenticatedSecurityRoute
  AuthenticatedSitesRoute: typeof AuthenticatedSitesRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedAdminPaymentsRoute: typeof AuthenticatedAdminPaymentsRoute
  AuthenticatedAdminServersRoute: typeof AuthenticatedAdminServersRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedAiRoute: AuthenticatedAiRoute,
  AuthenticatedChangePasswordRoute: AuthenticatedChangePasswordRoute,
  AuthenticatedCoursesRoute: AuthenticatedCoursesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDomainsRoute: AuthenticatedDomainsRoute,
  AuthenticatedEmailsRoute: AuthenticatedEmailsRoute,
  AuthenticatedHostingRoute: AuthenticatedHostingRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRoute,
  AuthenticatedLinkbioRoute: AuthenticatedLinkbioRoute,
  AuthenticatedMarketingRoute: AuthenticatedMarketingRoute,
  AuthenticatedMeuAudiovisualRoute: AuthenticatedMeuAudiovisualRoute,
  AuthenticatedMeuDesignRoute: AuthenticatedMeuDesignRoute,
  AuthenticatedReferralRoute: AuthenticatedReferralRoute,
  AuthenticatedSecurityRoute: AuthenticatedSecurityRoute,
  AuthenticatedSitesRoute: AuthenticatedSitesRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedAdminPaymentsRoute: AuthenticatedAdminPaymentsRoute,
  AuthenticatedAdminServersRoute: AuthenticatedAdminServersRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AudiovisualRoute: AudiovisualRoute,
  CertificadosSslRoute: CertificadosSslRoute,
  CheckoutRoute: CheckoutRoute,
  ContactoRoute: ContactoRoute,
  DesignRoute: DesignRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  NossoEscritorioRoute: NossoEscritorioRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  DominiosProtecaoWhoisRoute: DominiosProtecaoWhoisRoute,
  DominiosRegistrarRoute: DominiosRegistrarRoute,
  DominiosTransferirRoute: DominiosTransferirRoute,
  HospedagemCloudRoute: HospedagemCloudRoute,
  HospedagemEmailCorporativoRoute: HospedagemEmailCorporativoRoute,
  HospedagemRevendaWhmRoute: HospedagemRevendaWhmRoute,
  HospedagemWebRoute: HospedagemWebRoute,
  IaAutomacaoAutomacaoN8nRoute: IaAutomacaoAutomacaoN8nRoute,
  IaAutomacaoChatbotsIaRoute: IaAutomacaoChatbotsIaRoute,
  IaAutomacaoIaWhatsappRoute: IaAutomacaoIaWhatsappRoute,
  IaAutomacaoOpenclawRoute: IaAutomacaoOpenclawRoute,
  MarketingGestaoSocialRoute: MarketingGestaoSocialRoute,
  MarketingSeoPremiumRoute: MarketingSeoPremiumRoute,
  MarketingTrafegoPagoRoute: MarketingTrafegoPagoRoute,
  VpsCloudCloudPrivadaRoute: VpsCloudCloudPrivadaRoute,
  VpsCloudServidorDedicadoRoute: VpsCloudServidorDedicadoRoute,
  VpsCloudVpsNvmeRoute: VpsCloudVpsNvmeRoute,
  ApiPublicPaymentsMercadopagoWebhookRoute:
    ApiPublicPaymentsMercadopagoWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
